---
# tasks file for syslog

- name: Configure the standard Syslog settings
  tags:
    - syslog
  block:
    # First, determine whether it's necessary to remove any previously configured NTP settings
    - name: Capture show configuration output for Syslog cleanup
      tags: syslog_dry_run
      junipernetworks.junos.junos_command:
        commands:
          - "show configuration"
        display: set
      register: config_result
      when: config_output is not defined or config_output | length == 0

    - name: Save the configuration output to a variable
      tags: syslog_dry_run
      ansible.builtin.set_fact:
        config_output: "{{ config_result.stdout }}"
      when: config_result.stdout is defined and config_result.stdout | length > 0
    
    # No cleanup necessary by default. Leave existing syslog hosts if any are previously configured assuming more than one is fine
    - name: Build the Syslog cleanup values
      tags: syslog_dry_run
      ansible.builtin.set_fact:
        # the regex_findall will return a list of matching lines and the group causes it to return just server name or IP
        syslog_clear_servers: "{{ config_output | regex_findall('(?m)system syslog host ([\\w\\.-]+)') | unique }}"
      when: "'clear_syslog' in ansible_run_tags"

    - name: Build syslog.conf file from the template
      tags: syslog_dry_run
      ansible.builtin.template:
        src: syslog.j2
        dest: "{{ config_build }}/02_syslog.conf"

    # Setup filter ACLs for Syslog

    #- name: Include interface filter ACLs for Syslog
    #  tags: syslog_dry_run
    #  ansible.builtin.include_tasks:
    #    file: lo_filter.yml
    #    #apply:
    #    #  tags:
    #    #    - lo_filter
    #  when: "'syslog_acl' in ansible_run_tags or 'syslog_acl_dry_run' in ansible_run_tags"