---
- name: MVP Test
  # hosts: junos
  # Run with:
  # ansible-playbook ../mvp_test.yml -vvv --ask-vault-pass --tags mvp
  hosts: localhost
  # Run with:
  # ansible-playbook -vvv -i localhost, ../mvp_test.yml --tags mvp,debug,netconf_acl
  connection: local
  gather_facts: no
  vars:
    aaa_user_templates:
      - name: admin-template
        desc: "User template for remote super-users"
        uid: 2010
        class: super-user
      - name: operator-template
        desc: "User template for remote operator users"
        uid: 2011
        class: operator
  tags: mvp
  tasks:
    - name: Build a test_var directly
      ansible.builtin.set_fact:
        test_var: 
          - { name: 'testuser1', groups: 'wheel' }
          - { name: 'testuser2', groups: 'root' }

    - name: Show a combined list of users, plus user templates
      ansible.builtin.set_fact:
        test_var2: "{{ aaa_user_templates + test_var }}"
