---
# tasks file for AAA
- name: Configure the standard AAA settings
  tags:
    - aaa
  block:
    # First, build commands to remove any previously configured AAA servers
    - name: Capture show run command output for AAA cleanup
      tags: aaa_dry_run
      ansible.netcommon.cli_command:
        command: "show running-config"
      register: config_output

    - name: Build set of AAA cleanup commands
      tags: aaa_dry_run
      ansible.builtin.set_fact:
        # the regex_findall will collect just the portion of the lines from the device's config to use in the remove command
        # the regex_replace will match the reusable portion of the regex_findall and use the substitution to build the removal command
        aaa_clear_commands: "{{ config_output.stdout | regex_findall('(?m)radius-server host [\\w\\.-]+') | regex_replace('(?m)(radius-server host [\\w\\.-]+)', 'no \\1') }}"

    # Second, build commands to add the standard AAA configuration
    - name: Build set of new AAA configuration commands
      tags: aaa_dry_run
      ansible.builtin.set_fact:
        aaa_config_commands:
          - "radius-server host {{ aaa.ipv4 }} auth-port {{ radius_auth_port }} acct-port {{ radius_acct_port }} key {{ radius_secret }}"
          - "ip http authentication aaa login-authentication https radius local"
          - "aaa authentication login SSH radius local"
          - "aaa authentication enable SSH radius enable"
          - "aaa authentication login default radius local"
          - "aaa authentication enable default radius enable"
          - "aaa accounting login start-stop group radius"

    - name: List all of the AAA configuration commands that would be pushed
      tags: aaa_dry_run
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop: "{{ [ 'configure terminal' ] + aaa_clear_commands + aaa_config_commands + [ 'exit' ] }}"
      when: "'debug' in ansible_run_tags"

    - name: Push the AAA configuration
      ansible.netcommon.cli_command:
        command: "{{ item }}"
      loop: "{{ [ 'configure terminal' ] + aaa_clear_commands + aaa_config_commands + [ 'exit' ] }}"
      register: command_output
      changed_when: command_output.stdout|length <= 0

    - name: Show Debug command_output variable
      ansible.builtin.debug:
        msg: '{{ command_output }}'
      when: "'debug' in ansible_run_tags"

    - name: Check for Failutres in the Command's Output
      ansible.builtin.fail:
        msg: "The command ({{ item.item }}) did not have an empty response"
      when: item.stdout|length > 0
      loop: '{{ command_output.results }}'

    - name: Save Device Configuration
      ansible.netcommon.cli_command:
        command: "copy running-config startup-config"
      register: save_output
      failed_when: "'Copy succeeded' not in save_output.stdout"
