---
- name: Run junos roles
  hosts: junos
  roles:
    - assemble_apply
    - backup
    - netconf
    - src_ip
    - ntp
    - syslog
    - aaa
    - filter_acl
    - pw_reset
  gather_facts: false
  tasks:
    - name: Assemble all the configs and install them
      tags:
        - netconf_acl
        - netconf_acl_dry_run
        - ntp
        - ntp_acl
        - ntp_dry_run
        - ntp_acl_dry_run
        - aaa
        - aaa_acl
        - aaa_dry_run
        - aaa_acl_dry_run
        - syslog
        - syslog_acl
        - syslog_dry_run
        - syslog_acl_dry_run
        - pw_reset
        - pw_dry_run
      block:
        - name: Assemble the configs and check whether the commit handler should be run
          ansible.builtin.assemble:
            src: "{{ config_build }}"
            dest:  "{{ config_all }}"
            mode: 0640

        - name: Get stats on the assembled config
          ansible.builtin.stat:
            path: "{{ config_all }}"
          register: conf

        - name: Run the handler if the assembled config exists and isn't empty
          ansible.builtin.debug:
            msg: The assembled config is ready, running the handler to push it to the device
          changed_when: true
          notify: Install the config on the device
          when: conf.stat.size is defined and conf.stat.size > 0
