---
# handlers file for assemble_apply
- name: Handler to install the config on the device
  tags:
    - aaa
    - ntp
    - syslog
    - pw_reset
  block: 
    - name: Install the config on the device
      tags:
        - aaa_dry_run
        - ntp_dry_run
        - pw_dry_run
        - syslog_dry_run
      ansible.builtin.command: cat {{ config_all|quote }}
      register: command_output
      notify: Print the commands

    - name: Print the commands
      tags:
        - aaa_dry_run
        - ntp_dry_run
        - pw_dry_run
        - syslog_dry_run
      ansible.builtin.debug:
        msg: "{{ command_output.stdout }}"
      changed_when: true
      notify: Push the Full configuration

    # Loop through each command on the device and force an error if any command returns a response
    - name: Push the Full configuration
      ansible.netcommon.cli_command:
        command: "{{ item }}"
      loop: "{{ command_output.stdout_lines }}"
      register: cli_output
      when: "ansible_run_tags | select('match','.*dry_run') | list | length == 0"
      failed_when: cli_output.stdout|length > 0
      changed_when: cli_output.stdout|length == 0
    #  notify: Check for command failures

    #- name: Show Debug cli_output variable
    #  ansible.builtin.debug:
    #    msg: '{{ cli_output }}'
    #  when: "'debug' in ansible_run_tags"
    #  listen: Check for command failures

    #- name: Force failures if the command's had non-empty responses
    #  ansible.builtin.fail:
    #    msg: "The command ({{ item.item }}) did not have an empty response"
    #  when: item.stdout|length > 0
    #  loop: '{{ cli_output.results }}'
    #  listen: Check for command failures