---
# tasks file for syslog

- name: Configure the standard Syslog settings
  tags:
    - syslog
  block:
    - name: Build syslog.conf file from the template
      tags: syslog_dry_run
      ansible.builtin.template:
        src: syslog.j2
        dest: "{{ config_build }}/02_syslog.conf"
        mode: 0640
